[IMP] open_academy: Created session and partner models and related them with previously created course model; generated views to manage these relations T#53764
payen000/open_academy pull request #5
Opened 2022-01-13 19:06 UTC by payen000

A Session model was defined. Sessions relate to courses by their ids and have durations, instructors, attendees and starting dates.
![image](https://user-images.githubusercontent.com/49595803/149257043-72087da3-cb9b-4749-a229-a81920f1a7f8.png)

A responsible user field was defined for the course model and put in the form view.
![image](https://user-images.githubusercontent.com/49595803/149257177-f50f05cc-6640-40ec-8879-0a7fc54f820b.png)

Partners had their views inherited from the res.partner view using view inheritance. 
![image](https://user-images.githubusercontent.com/49595803/149393079-8010579a-0044-42e1-8ce8-ac27d85db26c.png)

Partners can manage the course sessions they will be attending to by clicking on the Open Academy sessions tab and adding a line from which the following window pops out:
![image](https://user-images.githubusercontent.com/49595803/149393151-f8c6ddc1-79ae-4317-a9c4-c50c63e49f38.png)

2022-01-13 19:09 UTC, payen000 commented
@Jerudiel @rolandojduartem Sorry about closing the other PR, I pushed the wrong branch and the PR disappeared! Anyway, would you review my code please? :)

2022-01-13 20:50 UTC, Jerudiel commented
+1 Looks good!

2022-01-13 22:38 UTC, rolandojduartem approved these changes
It looks good for me +1

2022-01-13 23:16 UTC, frahikLV requested changes
@payen000 can you address these changes?

2022-01-13 23:16 UTC, frahikLV commented on open_academy/__manifest__.py
> +        'views/inherited_partner.xml',
Rename the file as `partner.xml`

2022-01-13 23:16 UTC, frahikLV commented on open_academy/demo/session.xml
> +        <field name='course_id' ref='course_demo1'></field>
```suggestion
        <field name='course_id' ref='course_demo1'/>
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/demo/session.xml
> +        <field name='course_id' ref='course_demo1'></field>
```suggestion
        <field name='course_id' ref='course_demo1'/>

2022-01-13 23:16 UTC, frahikLV commented on open_academy/demo/session.xml
> +        <field name='course_id' ref='course_demo2'></field>
```suggestion
        <field name='course_id' ref='course_demo2'/>
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/models/__init__.py
> +from . import inherited_partner
Rename the model file as `partner.py`

```suggestion
from . import partner
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/models/inherited_partner.py
> +class InheritedPartner(models.Model):
```suggestion
class ResPartner(models.Model):
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/models/inherited_partner.py
> +	is_instructor = fields.Boolean('Is an instructor')
I don't know if you are trying to add some help in the field, if it is the case change to

```suggestion
	is_instructor = fields.Boolean(help='This partner is a session instructor?')
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/models/session.py
> +    start_date = fields.Date('Start date')
```suggestion
    start_date = fields.Date()
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/models/session.py
> +    duration = fields.Float('Duration')
If you are trying to add as string, Odoo automatically set the name field as `Duration` so we don't need replace to the same string

```suggestion
    duration = fields.Float()
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/views/inherited_partner.xml
> +            <field name='display_name' position='after'>
Nice!!! :blue_heart:

2022-01-13 23:16 UTC, frahikLV commented on open_academy/views/inherited_partner.xml
> +                    <label for='is_instructor' string='Is an instructor'/>
Remove this line
```suggestion
```

2022-01-13 23:16 UTC, frahikLV commented on open_academy/views/inherited_partner.xml
> +    <record id='partner_action_display_view' model='ir.actions.act_window'>
Why are you adding a new action to res.parter?

2022-01-13 23:16 UTC, frahikLV commented on open_academy/data/ir_ui_menu.xml
> +    <menuitem id='open_academy_partner_menu' name='Partners' action='partner_action_display_view' parent='open_academy.menu_open_academy_root' sequence='4'/>
don't create a new action to display contacts view, reuse the action on Contacts module

2022-01-13 23:16 UTC, frahikLV commented on open_academy/views/inherited_partner.xml
> +            <page name='internal_notes' position='after'>
Nice!!! :blue_heart:

2022-01-14 01:27 UTC, payen000 commented on open_academy/views/inherited_partner.xml
> +    <record id='partner_action_display_view' model='ir.actions.act_window'>
I didn't realize at the time that this wasn't necessary, and I mechanically followed the "recipe"
from the other views that I had already defined. But now I have used the power of the contacts module and used its action instead!

2022-01-14 02:01 UTC, payen000 commented
@frahikLV Done! Could you review my PR again, please? I PROMISE I DID IT RIGHT THIS TIME :)

2022-01-14 16:35 UTC, frahikLV requested changes
@payen000 can you address these changes?

2022-01-14 16:35 UTC, frahikLV commented on open_academy/models/session.py
> +    number_of_seats = fields.Integer('Seats')
Remove the string

```suggestion
    number_of_seats = fields.Integer()
```

2022-01-14 16:35 UTC, frahikLV commented on open_academy/demo/session.xml
> +    </record>
Remove the extra space

```suggestion
    </record>
```

2022-01-14 16:35 UTC, frahikLV commented on open_academy/demo/session.xml
> +        <field name='name'>Sesion 1</field>
Fix the Typo

2022-01-14 16:35 UTC, frahikLV commented on open_academy/demo/session.xml
> +        <field name='name'>Sesion 2</field>
Fix the Typo

2022-01-14 16:35 UTC, frahikLV commented on open_academy/demo/session.xml
> +        <field name='name'>Sesion 3</field>
Fix the Typo

2022-01-14 19:00 UTC, payen000 commented
@frahikLV I've finished my changes! Would you review, please? :) (sorry for needing so many reviews!)

2022-01-14 19:18 UTC, frahikLV approved these changes
@payen000 LGTM! 
I will merge this PR, ensure rebase your branch to get this changes

2022-01-14 19:18 UTC, merged