[IMP] open_academy: Added wizard model that enables users to register multiple attendees to multiple sessions at the same time; added spanish translation to module T#53764
payen000/open_academy pull request #9
Opened 2022-01-21 19:25 UTC by payen000

On the session tree view, selecting a sessions enables the 'register attendees' button on the header:
![register_button](https://user-images.githubusercontent.com/49595803/150587268-a04155c1-b890-4874-a8eb-756e6e9b2f57.png)

Clicking on this button displays the wizard, from which multiple attendees can be selected for registration:
![register_wizard](https://user-images.githubusercontent.com/49595803/150587415-13cdc053-38c5-45ba-8367-ef1cc2b3e881.png)

The wizard raises an error when trying to register more users than there are available seats:
![abort_register](https://user-images.githubusercontent.com/49595803/150587569-1ff1d486-abe2-4ab7-acc0-e8d5923ba269.png)

If the registration is successful, the sessions are updated to reflect this:
![finished_registering](https://user-images.githubusercontent.com/49595803/150587667-6a65a31e-fca7-48c3-95a1-2aca32d82382.png)

Finally, a spanish translation of the module is available:
![translation](https://user-images.githubusercontent.com/49595803/150587705-50734bf9-1033-426f-8e58-0d2703820ebd.png)

![image](https://user-images.githubusercontent.com/49595803/150587975-f49f2b85-a230-4b08-8b82-cf5a6a31adc0.png)

2022-01-21 19:28 UTC, payen000 commented
@frahikLV Hello again, would you review my code please? :)

2022-01-21 22:17 UTC, frahikLV requested changes
@payen000 can you address these changes?

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/__init__.py
> +from . import wizard_session
change all the references of the name of the wizard from `wizard_session` to `assign_atendee_sessions`

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/wizard_session.py
> +class WizardSession(models.TransientModel):
rename it

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/wizard_session.py
> +    _name = 'wizard_session'
modes `_name` don't use a underscore in the name, uses `.` , change this when you rename the wizard

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/wizard_session.py
> +    _description = 'Wizard Session'
rename

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/wizard_session.py
> +        return selected_session_ids
Remove this, please send the ids on the action call the ids via context with `default_session_ids` key

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/wizard_session.py
> +    session_ids = fields.Many2many('session', required=True, default=lambda self: self._default_session_ids())
```suggestion
    session_ids = fields.Many2many('session', required=True)
```

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/wizard_session.py
> +    @api.depends('session_ids', 'attendee_ids')
remove this

2022-01-21 22:17 UTC, frahikLV commented on open_academy/wizard/wizard_session.py
> +            raise ValidationError(_(error_message))
Refactor this code, please don't made a lot of talks to DB to update the `attendee_ids`, first check if the session has enough space, if not, show a UserError, not a ValidationError
If the sessions have space, made a `write` to all the records including with the `Command.link()` method

2022-01-21 22:18 UTC, frahikLV commented
@payen000 also fix your translation file... has a lot of lines, only translate the records related to your module

2022-01-22 03:36 UTC, payen000 commented
@frahikLV Sorry I couldn't finish sooner, I got a little stuck in a certain part... Would you review my code? If not, I understand, I will wait until monday with Germana :)

2022-01-24 16:08 UTC, payen000 commented
@goliveirab Hello, would you review my code please? :)

2022-01-24 22:48 UTC, merged